name: Deploy to VPS

on:
  pull_request:
    types: [closed]
    branches: ['main']
  push:
    branches:
      - 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_ACCESS_TOKEN_KEY: ${{ secrets.VITE_ACCESS_TOKEN_KEY }}
          VITE_SALT_KEY: ${{ secrets.VITE_SALT_KEY }}
          VITE_IV_KEY: ${{ secrets.VITE_IV_KEY }}
        run: npm run build

      - name: Setup SSH key
        run: |
          echo "$SSH_PRIVATE_KEY" > /tmp/private_key.pem
          chmod 600 /tmp/private_key.pem

      - name: Add SSH host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: 22
          privateKey: ${{ secrets.PRIVATE_KEY }}
          local: 'build'
          remote: '/var/www/pocket-kai'
          rmRemote: true

      - name: Clean up private key
        run: |
          rm /tmp/private_key.pem
