name: Deploy to VPS

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches: ['main']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_ACCESS_TOKEN_KEY: ${{ secrets.VITE_ACCESS_TOKEN_KEY }}
          VITE_SALT_KEY: ${{ secrets.VITE_SALT_KEY }}
          VITE_IV_KEY: ${{ secrets.VITE_IV_KEY }}
          VITE_YA_METRIKA_COUNTER: ${{ secrets.VITE_YA_METRIKA_COUNTER }}
        run: npm run build

      - name: Deploy to VPS
        uses: easingthemes/ssh-deploy@main
        with:
          ARGS: "-rlgoDzvc -i --delete"
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_PORT: $${{ secrets.PORT }}
          TARGET: /var/www/pocket-kai
          SOURCE: dist/
